version: '2.0'
services:
  cart:
    container_name: cart
    image: rkalluru/k06-cart:221
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
    depends_on:
      - catalogue
      - redis
  catalogue:
    container_name: catalogue
    image: rkalluru/k06-catalogue:222
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    image: rkalluru/k06-frontend:305
    ports:
      - "80:80"
    depends_on:
      - catalogue
  mongodb:
    image: rkalluru/k06-mongodb:225
    container_name: mongodb
  redis:
    image: redis
    container_name: redis
  mysql:
    container_name: mysql
    image: rkalluru/k06-mysql:303
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
  user:
    container_name: user
    image: rkalluru/k06-user:297
    environment:
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_HOST: redis
    depends_on:
      - mongodb
      - redis
  shipping:
    container_name: shipping
    image: rkalluru/k06-shipping:304
    environment:
      CART_ENDPOINT: "cart:7000"
      DB_HOST: mysql
    depends_on:
      - mysql
  payment:
    container_name: payment
    image: rkalluru/k06-payment:306
    environment:
      CART_HOST: cart
      USER_HOST: user
      AMQP_HOST: rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq